# Generated by Django 4.2.14 on 2024-07-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_md5password_sha1password_sha224password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='md5password',
            name='original_password',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passwords.password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sha1password',
            name='original_password',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passwords.password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sha224password',
            name='original_password',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passwords.password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sha256password',
            name='original_password',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passwords.password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sha3256password',
            name='original_password',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passwords.password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sha384password',
            name='original_password',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passwords.password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sha512password',
            name='original_password',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passwords.password'),
            preserve_default=False,
        ),
    ]
